name: Tag Build

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:        
      - staging.*

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Staging Build for Angular Project."
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Create and populate .env file
        env:
          AUTHENTICATION_TOKEN: ${{ secrets.AUTHENTICATION_TOKEN }}
          BASE_API_URL: ${{ secrets.BASE_API_URL }}
        run: |
          cat <<EOF > .env.production
          BASE_API_URL="$BASE_API_URL"
          AUTHENTICATION_TOKEN="$AUTHENTICATION_TOKEN"
          EOF

          cat <<EOF > .env.development
          BASE_API_URL="$BASE_API_URL"
          AUTHENTICATION_TOKEN="$AUTHENTICATION_TOKEN"
          EOF

          echo "cat .env.production"
          echo "cat .env.development"
          cat .env.development
          cat .env.production

      - name: Build Environment Files
        run: npm run env

      - name: Build Project
        run: npm run prod-build
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
